
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncjcsfnvyungxfmqszpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jamNzZm52eXVuZ3hmbXFzenB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNDk1MDMsImV4cCI6MjA2NDkyNTUwM30.RrXE-3htJRe2FUKwbgsSxsOASg-mNkuOApIDYcqh2Ns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

console.log('Supabase Client: Inicializando com URL:', SUPABASE_URL);

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'x-client-info': 'supabase-js-web'
    }
  },
  db: {
    schema: 'public'
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});

// Verificar conexão inicial
supabase.auth.onAuthStateChange((event, session) => {
  console.log('Supabase Client: Estado de autenticação mudou:', event, session?.user?.email || 'Nenhum usuário');
});

// Testar conectividade
supabase.auth.getSession().then(({ data: { session }, error }) => {
  if (error) {
    console.error('Supabase Client: Erro ao obter sessão:', error);
  } else {
    console.log('Supabase Client: Sessão atual:', session?.user?.email || 'Nenhuma sessão');
  }
});
