// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncjcsfnvyungxfmqszpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jamNzZm52eXVuZ3hmbXFzenB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNDk1MDMsImV4cCI6MjA2NDkyNTUwM30.RrXE-3htJRe2FUKwbgsSxsOASg-mNkuOApIDYcqh2Ns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);